# Generated by Django 4.1.4 on 2023-01-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_useraccount_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='home_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
