# Generated by Django 4.1.4 on 2023-01-14 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_useraccount_is_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='username',
        ),
    ]
