# Generated by Django 4.1.4 on 2023-01-02 10:17

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_corevalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('site_page_header_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('company_name', models.CharField(max_length=100)),
                ('CAC_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(max_length=50)),
                ('tag_line', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=14)),
                ('telephone_2', models.CharField(blank=True, max_length=14, null=True)),
                ('about_company', ckeditor.fields.RichTextField()),
                ('terms_and_conditions', ckeditor.fields.RichTextField()),
                ('privacy_policy', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Company Information',
            },
        ),
        migrations.AlterModelOptions(
            name='workprocess',
            options={'verbose_name_plural': 'Work Processes'},
        ),
        migrations.AlterField(
            model_name='corevalue',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='workprocess',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
