# Generated by Django 4.1.4 on 2023-05-09 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sportstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportstat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sportstats', to=settings.AUTH_USER_MODEL),
        ),
    ]
