# Generated by Django 4.1.4 on 2023-01-14 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_useraccount_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='date_joined',
        ),
    ]
