# Generated by Django 4.1.4 on 2023-01-02 10:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_companyinformation_alter_workprocess_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='privacy_policy',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='terms_and_conditions',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
