# Generated by Django 4.1.4 on 2023-01-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_companyinformation_privacy_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_figure', models.IntegerField()),
                ('stat_title', models.CharField(max_length=50)),
            ],
        ),
    ]
