# Generated by Django 4.1.4 on 2023-01-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_ourstory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourstory',
            options={'verbose_name_plural': 'Our Stories'},
        ),
    ]
