# Generated by Django 4.1.4 on 2023-01-02 12:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_ourstory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourstory',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
