# Generated by Django 4.1.4 on 2023-01-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_ourstory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_awesome_class', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
    ]
