# Generated by Django 4.1.4 on 2023-07-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_testimonial_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
