# Generated by Django 4.1.4 on 2023-07-20 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_blacklistedtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlacklistedToken',
        ),
    ]
