# Generated by Django 4.1.4 on 2023-01-03 17:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='site_page_header_image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
